version: "3.8"
services:
  server:
    build: ./LiarsDiceAPI
    ports:
      - "5000:5000"
  web:
    image: nginx:latest
    volumes:
      - ./WebClient/:/usr/share/nginx/html/
    ports:
      - "8080:80"